### ISSUE TITLE
Unable to retrieve data for get_activity: 'studio'

### ISSUE THREAD

**Issue by Brian-Watson** [Tautulli/Tautulli-Issues#135]
**Version:**
V2.1.22

**Branch:**

**Commit hash:**

**Operating system:**
Windows 10 (10.0.17134)

**Python version:**
2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]

*What you did?**
Started watching a recorded LiveTV sporting event.

**What happened?**
Activity now shows "There was an error communicating with your Plex Server. Check the logs and verify your server connection in the settings..

**What you expected?**

**How can we reproduce your issue?**
Just started watching a recorded NFL Game.

**What are your (relevant) settings?**

**Link to logs:**
I see this over and over in the logs...

`2018-10-28 21:41:27 - WARNING :: Thread-3 : Error parsing XML. duplicate attribute: line 3, column 508
2018-10-28 21:41:27 - WARNING :: Thread-3 : Tautulli Pmsconnect :: Unable to parse XML for get_metadata_details: 'list' object has no attribute 'getElementsByTagName'.
2018-10-28 21:41:27 - ERROR   :: Thread-3 : Tautulli WebSocket :: Failed to process session data: 'studio'.
2018-10-28 21:41:31 - WARNING :: Thread-3 : Error parsing XML. duplicate attribute: line 3, column 508
2018-10-28 21:41:31 - WARNING :: Thread-3 : Tautulli Pmsconnect :: Unable to parse XML for get_metadata_details: 'list' object has no attribute 'getElementsByTagName'.
2018-10-28 21:41:31 - ERROR   :: Thread-3 : Tautulli WebSocket :: Failed to process session data: 'studio'.
2018-10-28 21:41:34 - WARNING :: Thread-3 : Error parsing XML. duplicate attribute: line 3, column 508
2018-10-28 21:41:34 - WARNING :: Thread-3 : Tautulli Pmsconnect :: Unable to parse XML for get_metadata_details: 'list' object has no attribute 'getElementsByTagName'.
2018-10-28 21:41:34 - ERROR   :: Thread-3 : Tautulli WebSocket :: Failed to process session data: 'studio'.
2018-10-28 21:41:35 - WARNING :: CP Server Thread-13 : Error parsing XML. duplicate attribute: line 3, column 508
2018-10-28 21:41:35 - WARNING :: CP Server Thread-13 : Tautulli Pmsconnect :: Unable to parse XML for get_metadata_details: 'list' object has no attribute 'getElementsByTagName'.
2018-10-28 21:41:35 - ERROR   :: CP Server Thread-13 : Unable to retrieve data for get_activity: 'studio'
Traceback (most recent call last):
  File "C:\Tautulli\plexpy\webserve.py", line 5145, in get_activity
    result = pms_connect.get_current_activity()
  File "C:\Tautulli\plexpy\pmsconnect.py", line 1444, in get_current_activity
    session_output = self.get_session_each(session_)
  File "C:\Tautulli\plexpy\pmsconnect.py", line 1806, in get_session_each
    metadata_details = self.get_metadata_details(rating_key=rating_key, cache_key=session_key)
  File "C:\Tautulli\plexpy\pmsconnect.py", line 841, in get_metadata_details
    'studio': show_details['studio'],
KeyError: 'studio'
`

**Comment by JonnyWong16** [comment]
It's a Plex bug that I have already reported here: https://forums.plex.tv/t/tv-shows-returning-malformed-xml-metadata/320819

**Comment by Brian-Watson** [comment]
Okay, thanks!  I wonder if there is something that can be done in Tautulli to be more "defensive" with bad data like this, such as catching and logging the exception, but still allowing the Activity section to function?

**Comment by Brian-Watson** [comment]
Awesome, thanks!
