### ISSUE TITLE
v2.1.25 doesn't work ( database migration error ? )

### ISSUE THREAD

**Issue by thib3113** [Tautulli/Tautulli-Issues#137]
**Version:** v2.1.25 - Docker tautulli/tautulli:latest

**Branch:** master ?

**Commit hash:**
`
2018-11-04 13:27:49 - DEBUG :: MainThread : Git output: 56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28`

**Operating system:** Docker On an Ubuntu server 18.04 hosted on vmware on Windows server 2016

**Python version:** 2.7.15

**What you did?** nothing ( maybe a service update )

**What happened?** tautulli doesn't start web interface, and crash in loop : 
```
2018-11-04 13:27:44 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):,
2018-11-04 13:27:52 - ERROR :: MainThread : Tautulli Database :: Database error: no such column: agent,
2018-11-04 13:27:51 - INFO :: MainThread : Tautulli Users :: Requesting users list refresh...,
TypeError: 'NoneType' object is not iterable,
2018-11-04 13:27:51 - INFO :: MainThread : Tautulli Config :: Writing configuration to file,
2018-11-04 13:27:52 - WARNING :: MainThread : Tautulli Libraries :: Unable to execute database query for get_sections: no such column: agent.,
2018-11-04 13:27:52 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):,
  File "/app/tautulli/Tautulli.py", line 285, in <module>,
    main(),
  File "/app/tautulli/Tautulli.py", line 214, in main,
    plexpy.initialize(config_file),
  File "/app/tautulli/plexpy/__init__.py", line 293, in initialize,
    users.refresh_users(),
  File "/app/tautulli/plexpy/users.py", line 43, in refresh_users,
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs]),
Traceback (most recent call last):
```

**Other things : **  
- I've some backuped dbs in backup folder, so I can try to restore manually .
- It's worked before ( last check maybe in the last week )
- the App get an error from github, because asking to lot of time for a new version : 
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,
usermod: no changes,
,
------------------------------------,
  _______          _         _ _ _,
 |__   __|        | |       | | (_),
    | | __ _ _   _| |_ _   _| | |_,
    | |/ _` | | | | __| | | | | | |,
    | | (_| | |_| | |_| |_| | | | |,
    |_|\__,_|\__,_|\__|\__,_|_|_|_|,
,
------------------------------------,
GID/UID,
User uid:    911,
User gid:    911,
------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-install: executing... ,
Cloning into '/app/tautulli'...,
[cont-init.d] 30-install: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
2018-11-04 13:27:22 - INFO :: MainThread : Starting Tautulli v2.1.25,
2018-11-04 13:27:22 - INFO :: MainThread : Linux 4.15.0-38-generic (#41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018),
2018-11-04 13:27:22 - INFO :: MainThread : Europe/Paris (UTC+0100),
2018-11-04 13:27:22 - INFO :: MainThread : Python 2.7.15 (default, Aug 16 2018, 14:17:09) ,
[GCC 6.4.0],
2018-11-04 13:27:22 - INFO :: MainThread : Program Dir: /app/tautulli,
2018-11-04 13:27:22 - INFO :: MainThread : Config File: /config/config.ini,
2018-11-04 13:27:22 - INFO :: MainThread : Database File: /config/tautulli.db,
2018-11-04 13:27:22 - INFO :: MainThread : Checking if the database upgrades are required...,
2018-11-04 13:27:22 - ERROR :: MainThread : Can't connect to the database: database disk image is malformed,
2018-11-04 13:27:22 - INFO :: MainThread : Checking if configuration upgrades are required...,
2018-11-04 13:27:22 - DEBUG :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /app/tautulli,
2018-11-04 13:27:22 - DEBUG :: MainThread : Git output: 56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28,
2018-11-04 13:27:22 - DEBUG :: MainThread : Trying to execute: "git rev-parse --abbrev-ref --symbolic-full-name @{u}" with shell in /app/tautulli,
2018-11-04 13:27:22 - DEBUG :: MainThread : Git output: origin/master,
2018-11-04 13:27:22 - INFO :: MainThread : Retrieving latest version information from GitHub,
2018-11-04 13:27:22 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/Tautulli/Tautulli/commits/master,
2018-11-04 13:27:23 - ERROR :: MainThread : Request raise HTTP error with status code 403 (local client error).,
2018-11-04 13:27:23 - DEBUG :: MainThread : Server responded with message: {"message":"API rate limit exceeded for 78.***.***.***. (But here's the good news: Authenticated requests get a higher rate limit. Check out the docume...,
2018-11-04 13:27:23 - WARNING :: MainThread : Could not get the latest version from GitHub. Are you running a local development version?,
2018-11-04 13:27:23 - INFO :: MainThread : Tautulli PlexTV :: Requesting resources for server...,
2018-11-04 13:27:23 - INFO :: MainThread : Tautulli PlexTV :: Server URL retrieved.,
2018-11-04 13:27:24 - INFO :: MainThread : Tautulli Config :: Writing configuration to file,
2018-11-04 13:27:24 - INFO :: MainThread : Tautulli Users :: Requesting users list refresh...,
2018-11-04 13:27:25 - ERROR :: MainThread : Tautulli Database :: Database error: no such column: agent,
2018-11-04 13:27:25 - WARNING :: MainThread : Tautulli Libraries :: Unable to execute database query for get_sections: no such column: agent.,
2018-11-04 13:27:25 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):,
  File "/app/tautulli/Tautulli.py", line 285, in <module>,
    main(),
  File "/app/tautulli/Tautulli.py", line 214, in main,
    plexpy.initialize(config_file),
  File "/app/tautulli/plexpy/__init__.py", line 293, in initialize,
    users.refresh_users(),
  File "/app/tautulli/plexpy/users.py", line 43, in refresh_users,
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs]),
TypeError: 'NoneType' object is not iterable,
,
Traceback (most recent call last):,
  File "/app/tautulli/Tautulli.py", line 285, in <module>,
    main(),
  File "/app/tautulli/Tautulli.py", line 214, in main,
    plexpy.initialize(config_file),
  File "/app/tautulli/plexpy/__init__.py", line 293, in initialize,
    users.refresh_users(),
  File "/app/tautulli/plexpy/users.py", line 43, in refresh_users,
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs]),
TypeError: 'NoneType' object is not iterable,
2018-11-04 13:27:26 - INFO :: MainThread : Starting Tautulli v2.1.25,
2018-11-04 13:27:26 - INFO :: MainThread : Linux 4.15.0-38-generic (#41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018),
2018-11-04 13:27:26 - INFO :: MainThread : Europe/Paris (UTC+0100),
2018-11-04 13:27:26 - INFO :: MainThread : Python 2.7.15 (default, Aug 16 2018, 14:17:09) ,
[GCC 6.4.0],
2018-11-04 13:27:26 - INFO :: MainThread : Program Dir: /app/tautulli,
2018-11-04 13:27:26 - INFO :: MainThread : Config File: /config/config.ini,
2018-11-04 13:27:26 - INFO :: MainThread : Database File: /config/tautulli.db,
2018-11-04 13:27:26 - INFO :: MainThread : Checking if the database upgrades are required...,
2018-11-04 13:27:26 - ERROR :: MainThread : Can't connect to the database: database disk image is malformed,
2018-11-04 13:27:26 - INFO :: MainThread : Checking if configuration upgrades are required...,
2018-11-04 13:27:26 - DEBUG :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /app/tautulli,
2018-11-04 13:27:26 - DEBUG :: MainThread : Git output: 56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28,
2018-11-04 13:27:26 - DEBUG :: MainThread : Trying to execute: "git rev-parse --abbrev-ref --symbolic-full-name @{u}" with shell in /app/tautulli,
2018-11-04 13:27:26 - DEBUG :: MainThread : Git output: origin/master,
2018-11-04 13:27:26 - INFO :: MainThread : Retrieving latest version information from GitHub,
2018-11-04 13:27:26 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/Tautulli/Tautulli/commits/master,
2018-11-04 13:27:27 - ERROR :: MainThread : Request raise HTTP error with status code 403 (local client error).,
2018-11-04 13:27:27 - DEBUG :: MainThread : Server responded with message: {"message":"API rate limit exceeded for 78.***.***.***. (But here's the good news: Authenticated requests get a higher rate limit. Check out the docume...,
2018-11-04 13:27:27 - WARNING :: MainThread : Could not get the latest version from GitHub. Are you running a local development version?,
2018-11-04 13:27:27 - INFO :: MainThread : Tautulli PlexTV :: Requesting resources for server...,
2018-11-04 13:27:28 - INFO :: MainThread : Tautulli PlexTV :: Server URL retrieved.,
2018-11-04 13:27:28 - INFO :: MainThread : Tautulli Config :: Writing configuration to file,
2018-11-04 13:27:28 - INFO :: MainThread : Tautulli Users :: Requesting users list refresh...,
2018-11-04 13:27:29 - ERROR :: MainThread : Tautulli Database :: Database error: no such column: agent,
2018-11-04 13:27:29 - WARNING :: MainThread : Tautulli Libraries :: Unable to execute database query for get_sections: no such column: agent.,
2018-11-04 13:27:29 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):,
  File "/app/tautulli/Tautulli.py", line 285, in <module>,
    main(),
  File "/app/tautulli/Tautulli.py", line 214, in main,
    plexpy.initialize(config_file),
  File "/app/tautulli/plexpy/__init__.py", line 293, in initialize,
    users.refresh_users(),
  File "/app/tautulli/plexpy/users.py", line 43, in refresh_users,
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs]),
TypeError: 'NoneType' object is not iterable,
,
Traceback (most recent call last):,
  File "/app/tautulli/Tautulli.py", line 285, in <module>,
    main(),
  File "/app/tautulli/Tautulli.py", line 214, in main,
    plexpy.initialize(config_file),
  File "/app/tautulli/plexpy/__init__.py", line 293, in initialize,
    users.refresh_users(),
  File "/app/tautulli/plexpy/users.py", line 43, in refresh_users,
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs]),
TypeError: 'NoneType' object is not iterable,
2018-11-04 13:27:31 - INFO :: MainThread : Starting Tautulli v2.1.25,
2018-11-04 13:27:31 - INFO :: MainThread : Linux 4.15.0-38-generic (#41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018),
2018-11-04 13:27:31 - INFO :: MainThread : Europe/Paris (UTC+0100),
2018-11-04 13:27:31 - INFO :: MainThread : Python 2.7.15 (default, Aug 16 2018, 14:17:09) ,
[GCC 6.4.0],
2018-11-04 13:27:31 - INFO :: MainThread : Program Dir: /app/tautulli,
2018-11-04 13:27:31 - INFO :: MainThread : Config File: /config/config.ini,
2018-11-04 13:27:31 - INFO :: MainThread : Database File: /config/tautulli.db,
2018-11-04 13:27:31 - INFO :: MainThread : Checking if the database upgrades are required...,
2018-11-04 13:27:31 - ERROR :: MainThread : Can't connect to the database: database disk image is malformed,
2018-11-04 13:27:31 - INFO :: MainThread : Checking if configuration upgrades are required...,
2018-11-04 13:27:31 - DEBUG :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /app/tautulli,
2018-11-04 13:27:31 - DEBUG :: MainThread : Git output: 56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28,
2018-11-04 13:27:31 - DEBUG :: MainThread : Trying to execute: "git rev-parse --abbrev-ref --symbolic-full-name @{u}" with shell in /app/tautulli,
2018-11-04 13:27:31 - DEBUG :: MainThread : Git output: origin/master,
2018-11-04 13:27:31 - INFO :: MainThread : Retrieving latest version information from GitHub,
2018-11-04 13:27:31 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/Tautulli/Tautulli/commits/master,
2018-11-04 13:27:32 - ERROR :: MainThread : Request raise HTTP error with status code 403 (local client error).,
2018-11-04 13:27:32 - DEBUG :: MainThread : Server responded with message: {"message":"API rate limit exceeded for 78.***.***.***. (But here's the good news: Authenticated requests get a higher rate limit. Check out the docume...,
2018-11-04 13:27:32 - WARNING :: MainThread : Could not get the latest version from GitHub. Are you running a local development version?,
2018-11-04 13:27:32 - INFO :: MainThread : Tautulli PlexTV :: Requesting resources for server...,
2018-11-04 13:27:32 - INFO :: MainThread : Tautulli PlexTV :: Server URL retrieved.,
2018-11-04 13:27:32 - INFO :: MainThread : Tautulli Config :: Writing configuration to file,
2018-11-04 13:27:32 - INFO :: MainThread : Tautulli Users :: Requesting users list refresh...,
2018-11-04 13:27:33 - ERROR :: MainThread : Tautulli Database :: Database error: no such column: agent,
2018-11-04 13:27:33 - WARNING :: MainThread : Tautulli Libraries :: Unable to execute database query for get_sections: no such column: agent.,
2018-11-04 13:27:33 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):,
  File "/app/tautulli/Tautulli.py", line 285, in <module>,
    main(),
  File "/app/tautulli/Tautulli.py", line 214, in main,
    plexpy.initialize(config_file),
  File "/app/tautulli/plexpy/__init__.py", line 293, in initialize,
    users.refresh_users(),
  File "/app/tautulli/plexpy/users.py", line 43, in refresh_users,
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs]),
TypeError: 'NoneType' object is not iterable,
,
Traceback (most recent call last):,
  File "/app/tautulli/Tautulli.py", line 285, in <module>,
    main(),
  File "/app/tautulli/Tautulli.py", line 214, in main,
    plexpy.initialize(config_file),
  File "/app/tautulli/plexpy/__init__.py", line 293, in initialize,
    users.refresh_users(),
  File "/app/tautulli/plexpy/users.py", line 43, in refresh_users,
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs]),
TypeError: 'NoneType' object is not iterable,
2018-11-04 13:27:36 - INFO :: MainThread : Starting Tautulli v2.1.25,
2018-11-04 13:27:36 - INFO :: MainThread : Linux 4.15.0-38-generic (#41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018),
2018-11-04 13:27:36 - INFO :: MainThread : Europe/Paris (UTC+0100),
2018-11-04 13:27:36 - INFO :: MainThread : Python 2.7.15 (default, Aug 16 2018, 14:17:09) ,
[GCC 6.4.0],
2018-11-04 13:27:36 - INFO :: MainThread : Program Dir: /app/tautulli,
2018-11-04 13:27:36 - INFO :: MainThread : Config File: /config/config.ini,
2018-11-04 13:27:36 - INFO :: MainThread : Database File: /config/tautulli.db,
2018-11-04 13:27:36 - INFO :: MainThread : Checking if the database upgrades are required...,
2018-11-04 13:27:36 - ERROR :: MainThread : Can't connect to the database: database disk image is malformed,
2018-11-04 13:27:36 - INFO :: MainThread : Checking if configuration upgrades are required...,
2018-11-04 13:27:36 - DEBUG :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /app/tautulli,
2018-11-04 13:27:36 - DEBUG :: MainThread : Git output: 56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28,
2018-11-04 13:27:36 - DEBUG :: MainThread : Trying to execute: "git rev-parse --abbrev-ref --symbolic-full-name @{u}" with shell in /app/tautulli,
2018-11-04 13:27:36 - DEBUG :: MainThread : Git output: origin/master,
2018-11-04 13:27:36 - INFO :: MainThread : Retrieving latest version information from GitHub,
2018-11-04 13:27:36 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/Tautulli/Tautulli/commits/master,
2018-11-04 13:27:37 - ERROR :: MainThread : Request raise HTTP error with status code 403 (local client error).,
2018-11-04 13:27:37 - DEBUG :: MainThread : Server responded with message: {"message":"API rate limit exceeded for 78.***.***.***. (But here's the good news: Authenticated requests get a higher rate limit. Check out the docume...,
2018-11-04 13:27:37 - WARNING :: MainThread : Could not get the latest version from GitHub. Are you running a local development version?,
2018-11-04 13:27:37 - INFO :: MainThread : Tautulli PlexTV :: Requesting resources for server...,
2018-11-04 13:27:38 - INFO :: MainThread : Tautulli PlexTV :: Server URL retrieved.,
2018-11-04 13:27:38 - INFO :: MainThread : Tautulli Config :: Writing configuration to file,
2018-11-04 13:27:38 - INFO :: MainThread : Tautulli Users :: Requesting users list refresh...,
2018-11-04 13:27:39 - ERROR :: MainThread : Tautulli Database :: Database error: no such column: agent,
2018-11-04 13:27:39 - WARNING :: MainThread : Tautulli Libraries :: Unable to execute database query for get_sections: no such column: agent.,
2018-11-04 13:27:39 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):,
  File "/app/tautulli/Tautulli.py", line 285, in <module>,
    main(),
  File "/app/tautulli/Tautulli.py", line 214, in main,
    plexpy.initialize(config_file),
  File "/app/tautulli/plexpy/__init__.py", line 293, in initialize,
    users.refresh_users(),
  File "/app/tautulli/plexpy/users.py", line 43, in refresh_users,
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs]),
TypeError: 'NoneType' object is not iterable,
,
Traceback (most recent call last):,
  File "/app/tautulli/Tautulli.py", line 285, in <module>,
    main(),
  File "/app/tautulli/Tautulli.py", line 214, in main,
    plexpy.initialize(config_file),
  File "/app/tautulli/plexpy/__init__.py", line 293, in initialize,
    users.refresh_users(),
  File "/app/tautulli/plexpy/users.py", line 43, in refresh_users,
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs]),
TypeError: 'NoneType' object is not iterable,
2018-11-04 13:27:41 - INFO :: MainThread : Starting Tautulli v2.1.25,
2018-11-04 13:27:41 - INFO :: MainThread : Linux 4.15.0-38-generic (#41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018),
2018-11-04 13:27:41 - INFO :: MainThread : Europe/Paris (UTC+0100),
2018-11-04 13:27:41 - INFO :: MainThread : Python 2.7.15 (default, Aug 16 2018, 14:17:09) ,
[GCC 6.4.0],
2018-11-04 13:27:41 - INFO :: MainThread : Program Dir: /app/tautulli,
2018-11-04 13:27:41 - INFO :: MainThread : Config File: /config/config.ini,
2018-11-04 13:27:41 - INFO :: MainThread : Database File: /config/tautulli.db,
2018-11-04 13:27:41 - INFO :: MainThread : Checking if the database upgrades are required...,
2018-11-04 13:27:41 - ERROR :: MainThread : Can't connect to the database: database disk image is malformed,
2018-11-04 13:27:41 - INFO :: MainThread : Checking if configuration upgrades are required...,
2018-11-04 13:27:41 - DEBUG :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /app/tautulli,
2018-11-04 13:27:41 - DEBUG :: MainThread : Git output: 56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28,
2018-11-04 13:27:41 - DEBUG :: MainThread : Trying to execute: "git rev-parse --abbrev-ref --symbolic-full-name @{u}" with shell in /app/tautulli,
2018-11-04 13:27:41 - DEBUG :: MainThread : Git output: origin/master,
2018-11-04 13:27:41 - INFO :: MainThread : Retrieving latest version information from GitHub,
2018-11-04 13:27:41 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/Tautulli/Tautulli/commits/master,
2018-11-04 13:27:41 - ERROR :: MainThread : Request raise HTTP error with status code 403 (local client error).,
2018-11-04 13:27:41 - DEBUG :: MainThread : Server responded with message: {"message":"API rate limit exceeded for 78.***.***.***. (But here's the good news: Authenticated requests get a higher rate limit. Check out the docume...,
2018-11-04 13:27:41 - WARNING :: MainThread : Could not get the latest version from GitHub. Are you running a local development version?,
2018-11-04 13:27:41 - INFO :: MainThread : Tautulli PlexTV :: Requesting resources for server...,
2018-11-04 13:27:42 - INFO :: MainThread : Tautulli PlexTV :: Server URL retrieved.,
2018-11-04 13:27:42 - INFO :: MainThread : Tautulli Config :: Writing configuration to file,
2018-11-04 13:27:42 - INFO :: MainThread : Tautulli Users :: Requesting users list refresh...,
2018-11-04 13:27:44 - ERROR :: MainThread : Tautulli Database :: Database error: no such column: agent,
2018-11-04 13:27:44 - WARNING :: MainThread : Tautulli Libraries :: Unable to execute database query for get_sections: no such column: agent.,
2018-11-04 13:27:44 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):,
  File "/app/tautulli/Tautulli.py", line 285, in <module>,
    main(),
  File "/app/tautulli/Tautulli.py", line 214, in main,
    plexpy.initialize(config_file),
  File "/app/tautulli/plexpy/__init__.py", line 293, in initialize,
    users.refresh_users(),
  File "/app/tautulli/plexpy/users.py", line 43, in refresh_users,
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs]),
TypeError: 'NoneType' object is not iterable,
,
Traceback (most recent call last):,
  File "/app/tautulli/Tautulli.py", line 285, in <module>,
    main(),
  File "/app/tautulli/Tautulli.py", line 214, in main,
    plexpy.initialize(config_file),
  File "/app/tautulli/plexpy/__init__.py", line 293, in initialize,
    users.refresh_users(),
  File "/app/tautulli/plexpy/users.py", line 43, in refresh_users,
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs]),
TypeError: 'NoneType' object is not iterable,
2018-11-04 13:27:45 - INFO :: MainThread : Starting Tautulli v2.1.25,
2018-11-04 13:27:45 - INFO :: MainThread : Linux 4.15.0-38-generic (#41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018),
2018-11-04 13:27:45 - INFO :: MainThread : Europe/Paris (UTC+0100),
2018-11-04 13:27:45 - INFO :: MainThread : Python 2.7.15 (default, Aug 16 2018, 14:17:09) ,
[GCC 6.4.0],
2018-11-04 13:27:45 - INFO :: MainThread : Program Dir: /app/tautulli,
2018-11-04 13:27:45 - INFO :: MainThread : Config File: /config/config.ini,
2018-11-04 13:27:45 - INFO :: MainThread : Database File: /config/tautulli.db,
2018-11-04 13:27:45 - INFO :: MainThread : Checking if the database upgrades are required...,
2018-11-04 13:27:45 - ERROR :: MainThread : Can't connect to the database: database disk image is malformed,
2018-11-04 13:27:45 - INFO :: MainThread : Checking if configuration upgrades are required...,
2018-11-04 13:27:45 - DEBUG :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /app/tautulli,
2018-11-04 13:27:45 - DEBUG :: MainThread : Git output: 56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28,
2018-11-04 13:27:45 - DEBUG :: MainThread : Trying to execute: "git rev-parse --abbrev-ref --symbolic-full-name @{u}" with shell in /app/tautulli,
2018-11-04 13:27:45 - DEBUG :: MainThread : Git output: origin/master,
2018-11-04 13:27:45 - INFO :: MainThread : Retrieving latest version information from GitHub,
2018-11-04 13:27:46 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/Tautulli/Tautulli/commits/master,
2018-11-04 13:27:46 - ERROR :: MainThread : Request raise HTTP error with status code 403 (local client error).,
2018-11-04 13:27:46 - DEBUG :: MainThread : Server responded with message: {"message":"API rate limit exceeded for 78.***.***.***. (But here's the good news: Authenticated requests get a higher rate limit. Check out the docume...,
2018-11-04 13:27:46 - WARNING :: MainThread : Could not get the latest version from GitHub. Are you running a local development version?,
2018-11-04 13:27:46 - INFO :: MainThread : Tautulli PlexTV :: Requesting resources for server...,
2018-11-04 13:27:47 - INFO :: MainThread : Tautulli PlexTV :: Server URL retrieved.,
2018-11-04 13:27:47 - INFO :: MainThread : Tautulli Config :: Writing configuration to file,
2018-11-04 13:27:47 - INFO :: MainThread : Tautulli Users :: Requesting users list refresh...,
2018-11-04 13:27:48 - ERROR :: MainThread : Tautulli Database :: Database error: no such column: agent,
2018-11-04 13:27:48 - WARNING :: MainThread : Tautulli Libraries :: Unable to execute database query for get_sections: no such column: agent.,
2018-11-04 13:27:48 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):,
  File "/app/tautulli/Tautulli.py", line 285, in <module>,
    main(),
  File "/app/tautulli/Tautulli.py", line 214, in main,
    plexpy.initialize(config_file),
  File "/app/tautulli/plexpy/__init__.py", line 293, in initialize,
    users.refresh_users(),
  File "/app/tautulli/plexpy/users.py", line 43, in refresh_users,
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs]),
TypeError: 'NoneType' object is not iterable,
,
Traceback (most recent call last):,
  File "/app/tautulli/Tautulli.py", line 285, in <module>,
    main(),
  File "/app/tautulli/Tautulli.py", line 214, in main,
    plexpy.initialize(config_file),
  File "/app/tautulli/plexpy/__init__.py", line 293, in initialize,
    users.refresh_users(),
  File "/app/tautulli/plexpy/users.py", line 43, in refresh_users,
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs]),
TypeError: 'NoneType' object is not iterable,
2018-11-04 13:27:49 - INFO :: MainThread : Starting Tautulli v2.1.25,
2018-11-04 13:27:49 - INFO :: MainThread : Linux 4.15.0-38-generic (#41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018),
2018-11-04 13:27:49 - INFO :: MainThread : Europe/Paris (UTC+0100),
2018-11-04 13:27:49 - INFO :: MainThread : Python 2.7.15 (default, Aug 16 2018, 14:17:09) ,
[GCC 6.4.0],
2018-11-04 13:27:49 - INFO :: MainThread : Program Dir: /app/tautulli,
2018-11-04 13:27:49 - INFO :: MainThread : Config File: /config/config.ini,
2018-11-04 13:27:49 - INFO :: MainThread : Database File: /config/tautulli.db,
2018-11-04 13:27:49 - INFO :: MainThread : Checking if the database upgrades are required...,
2018-11-04 13:27:49 - ERROR :: MainThread : Can't connect to the database: database disk image is malformed,
2018-11-04 13:27:49 - INFO :: MainThread : Checking if configuration upgrades are required...,
2018-11-04 13:27:49 - DEBUG :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /app/tautulli,
2018-11-04 13:27:49 - DEBUG :: MainThread : Git output: 56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28,
2018-11-04 13:27:49 - DEBUG :: MainThread : Trying to execute: "git rev-parse --abbrev-ref --symbolic-full-name @{u}" with shell in /app/tautulli,
2018-11-04 13:27:49 - DEBUG :: MainThread : Git output: origin/master,
2018-11-04 13:27:49 - INFO :: MainThread : Retrieving latest version information from GitHub,
2018-11-04 13:27:49 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/Tautulli/Tautulli/commits/master,
2018-11-04 13:27:50 - ERROR :: MainThread : Request raise HTTP error with status code 403 (local client error).,
2018-11-04 13:27:50 - DEBUG :: MainThread : Server responded with message: {"message":"API rate limit exceeded for 78.***.***.***. (But here's the good news: Authenticated requests get a higher rate limit. Check out the docume...,
2018-11-04 13:27:50 - WARNING :: MainThread : Could not get the latest version from GitHub. Are you running a local development version?,
2018-11-04 13:27:50 - INFO :: MainThread : Tautulli PlexTV :: Requesting resources for server...,
2018-11-04 13:27:51 - INFO :: MainThread : Tautulli PlexTV :: Server URL retrieved.,
2018-11-04 13:27:51 - INFO :: MainThread : Tautulli Config :: Writing configuration to file,
2018-11-04 13:27:51 - INFO :: MainThread : Tautulli Users :: Requesting users list refresh...,
2018-11-04 13:27:52 - ERROR :: MainThread : Tautulli Database :: Database error: no such column: agent,
2018-11-04 13:27:52 - WARNING :: MainThread : Tautulli Libraries :: Unable to execute database query for get_sections: no such column: agent.,
2018-11-04 13:27:52 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):,
  File "/app/tautulli/Tautulli.py", line 285, in <module>,
    main(),
  File "/app/tautulli/Tautulli.py", line 214, in main,
    plexpy.initialize(config_file),
  File "/app/tautulli/plexpy/__init__.py", line 293, in initialize,
    users.refresh_users(),
  File "/app/tautulli/plexpy/users.py", line 43, in refresh_users,
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs]),
TypeError: 'NoneType' object is not iterable,
,
Traceback (most recent call last):,
  File "/app/tautulli/Tautulli.py", line 285, in <module>,
    main(),
  File "/app/tautulli/Tautulli.py", line 214, in main,
    plexpy.initialize(config_file),
  File "/app/tautulli/plexpy/__init__.py", line 293, in initialize,
    users.refresh_users(),
  File "/app/tautulli/plexpy/users.py", line 43, in refresh_users,
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs]),
TypeError: 'NoneType' object is not iterable,`

**Comment by JonnyWong16** [comment]
https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q18
