### ISSUE TITLE
Upgrading from v2.1.22 -> v2.1.25 fails to upgrade DB due to missing on_created column.

### ISSUE THREAD

**Issue by ziggimon** [Tautulli/Tautulli-Issues#138]
Tautilli logfile reports that v2.1.25 can't upgrade the DB.

```
2018-11-06 11:24:33 - INFO    :: MainThread : Checking if the database upgrades are required...
2018-11-06 11:24:33 - DEBUG   :: MainThread : Altering database. Updating database table notify_log.
2018-11-06 11:24:33 - ERROR   :: MainThread : Can't connect to the database: no such column: on_created
2018-11-06 11:24:33 - INFO    :: MainThread : Checking if configuration upgrades are required...
2018-11-06 11:24:33 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /opt/plexpy
2018-11-06 11:24:33 - DEBUG   :: MainThread : Git output: 56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28
2018-11-06 11:24:33 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref --symbolic-full-name @{u}" with shell in /opt/plexpy
2018-11-06 11:24:33 - DEBUG   :: MainThread : Git output: origin/master
2018-11-06 11:24:33 - INFO    :: MainThread : Retrieving latest version information from GitHub
2018-11-06 11:24:33 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/Tautulli/Tautulli/commits/master
2018-11-06 11:24:34 - DEBUG   :: MainThread : Latest version is 56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28
2018-11-06 11:24:34 - INFO    :: MainThread : Tautulli is up to date
2018-11-06 11:24:34 - INFO    :: MainThread : Tautulli Config :: Writing configuration to file
2018-11-06 11:24:34 - INFO    :: MainThread : Tautulli PlexTV :: Requesting resources for server...
2018-11-06 11:24:34 - INFO    :: MainThread : Tautulli PlexTV :: Using user-defined URL.
2018-11-06 11:24:34 - INFO    :: MainThread : Tautulli Config :: Writing configuration to file
2018-11-06 11:24:34 - INFO    :: MainThread : Tautulli Users :: Requesting users list refresh...
2018-11-06 11:24:36 - ERROR   :: MainThread : Tautulli Database :: Database error: no such column: agent
2018-11-06 11:24:36 - WARNING :: MainThread : Tautulli Libraries :: Unable to execute database query for get_sections: no such column: agent.
2018-11-06 11:24:36 - ERROR   :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "/opt/plexpy/PlexPy.py", line 28, in <module>
    main()
  File "/opt/plexpy/Tautulli.py", line 214, in main
    plexpy.initialize(config_file)
  File "/opt/plexpy/plexpy/__init__.py", line 293, in initialize
    users.refresh_users()
  File "/opt/plexpy/plexpy/users.py", line 43, in refresh_users
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs])
TypeError: 'NoneType' object is not iterable
```

**Version:**
v2.1.25

**Branch:**
Used tag: v2.1.25

**Commit hash:**
56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28

**Operating system:**
Linux - Ubuntu 16.04

**Python version:**
Python 2.7.12

**What you did?**
Upgraded from v2.1.22 -> v2.1.25

**What happened?**
DB failed to upgrade and it crashed

**What you expected?**
That it started and continued where it left off.

**How can we reproduce your issue?**
Upgrade to v.2.1.25 from v2.1.22 and start Tautulli.

**Link to logs:**
https://gist.github.com/ziggimon/c1272fe93f31636f9fa5e80e6387e5f9

**Comment by samwiseg00** [comment]
You have a corrupted DB.
https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q18

**Comment by ziggimon** [comment]
I've even exported and imported the db to a new file. Still same issue.

**Comment by JonnyWong16** [comment]
`DROP table notify_log;`

**Comment by ziggimon** [comment]
That gets things going a bit further, but it goes to hang on missing column filter_music:

```
2018-11-06 15:41:47 - INFO    :: MainThread : Program Dir: /opt/plexpy
2018-11-06 15:41:47 - INFO    :: MainThread : Config File: /opt/plexpy/config.ini
2018-11-06 15:41:47 - INFO    :: MainThread : Database File: /opt/plexpy/tautulli.db
2018-11-06 15:41:47 - INFO    :: MainThread : Checking if the database upgrades are required...
2018-11-06 15:41:47 - DEBUG   :: MainThread : Altering database. Updating database table notify_log.
2018-11-06 15:41:47 - DEBUG   :: MainThread : Altering database. Updating database table library_sections.
2018-11-06 15:41:47 - DEBUG   :: MainThread : Altering database. Removing unique constraint on username from users table.
2018-11-06 15:41:47 - DEBUG   :: MainThread : Altering database. Updating database table notifiers.
2018-11-06 15:41:47 - DEBUG   :: MainThread : Altering database. Updating database table user_login.
2018-11-06 15:41:47 - INFO    :: MainThread : Checking if configuration upgrades are required...
2018-11-06 15:41:47 - DEBUG   :: MainThread : Trying to execute: "git rev-parse HEAD" with shell in /opt/plexpy
2018-11-06 15:41:47 - DEBUG   :: MainThread : Git output: 56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28
2018-11-06 15:41:47 - DEBUG   :: MainThread : Trying to execute: "git rev-parse --abbrev-ref --symbolic-full-name @{u}" with shell in /opt/plexpy
2018-11-06 15:41:47 - DEBUG   :: MainThread : Git output: origin/master
2018-11-06 15:41:47 - INFO    :: MainThread : Retrieving latest version information from GitHub
2018-11-06 15:41:47 - DEBUG   :: MainThread : Requesting URL via GET method: https://api.github.com/repos/Tautulli/Tautulli/commits/master
2018-11-06 15:41:47 - DEBUG   :: MainThread : Latest version is 56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28
2018-11-06 15:41:47 - INFO    :: MainThread : Tautulli is up to date
2018-11-06 15:41:47 - INFO    :: MainThread : Tautulli Config :: Writing configuration to file
2018-11-06 15:41:47 - INFO    :: MainThread : Tautulli PlexTV :: Requesting resources for server...
2018-11-06 15:41:48 - INFO    :: MainThread : Tautulli PlexTV :: Using user-defined URL.
2018-11-06 15:41:48 - INFO    :: MainThread : Tautulli Config :: Writing configuration to file
2018-11-06 15:41:48 - INFO    :: MainThread : Tautulli Users :: Requesting users list refresh...
2018-11-06 15:41:50 - ERROR   :: MainThread : Tautulli Database :: Database error: no such column: filter_music
2018-11-06 15:41:50 - ERROR   :: MainThread : Uncaught exception: Traceback (most recent call last):
```

So it feels as some data may have been added between upgrades that my DB has missed.

**Comment by ziggimon** [comment]
Right so stepping to v2.1.24-beta before going to v2.1.25 solved the upgrade issue. Its now running on v2.1.25.

**Comment by JonnyWong16** [comment]
`DROP table users;`
