### ISSUE TITLE
ERROR Loading the Tautulli

### ISSUE THREAD

**Issue by BlackS0ull** [Tautulli/Tautulli-Issues#140]
c:\PlexTV\Tautulli-Tautulli-244008d>Tautulli.py
2018-11-08 10:16:28 - INFO :: MainThread : Starting Tautulli v2.1.25
2018-11-08 10:16:28 - INFO :: MainThread : Windows 10 (10.0.17134)
2018-11-08 10:16:28 - INFO :: MainThread : Europe/Bucharest (UTC+0200)
2018-11-08 10:16:28 - INFO :: MainThread : Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
2018-11-08 10:16:28 - INFO :: MainThread : Program Dir: C:\PlexTV\Tautulli-Tautulli-244008d
2018-11-08 10:16:28 - INFO :: MainThread : Config File: C:\PlexTV\Tautulli-Tautulli-244008d\config.ini
2018-11-08 10:16:28 - INFO :: MainThread : Database File: C:\PlexTV\Tautulli-Tautulli-244008d\tautulli.db
2018-11-08 10:16:28 - INFO :: MainThread : Checking if the database upgrades are required...
2018-11-08 10:16:28 - ERROR :: MainThread : Can't connect to the database: database disk image is malformed
2018-11-08 10:16:28 - INFO :: MainThread : Checking if configuration upgrades are required...
2018-11-08 10:16:28 - INFO :: MainThread : Retrieving latest version information from GitHub
2018-11-08 10:16:28 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/Tautulli/Tautulli/commits/beta
2018-11-08 10:16:29 - DEBUG :: MainThread : Latest version is 56a91de2c4ff0fdd8fbdff4dd7d7677bd16a4b28
2018-11-08 10:16:29 - INFO :: MainThread : Tautulli is up to date
2018-11-08 10:16:29 - INFO :: MainThread : Tautulli PlexTV :: Requesting resources for server...
2018-11-08 10:16:29 - DEBUG :: MainThread : Tautulli PlexTV :: Plex Pass subscription not found.
2018-11-08 10:16:29 - INFO :: MainThread : Tautulli PlexTV :: Using user-defined URL.
2018-11-08 10:16:29 - INFO :: MainThread : Tautulli Config :: Writing configuration to file
2018-11-08 10:16:29 - INFO :: MainThread : Tautulli Users :: Requesting users list refresh...
2018-11-08 10:16:30 - ERROR :: MainThread : Tautulli Database :: Database error: no such column: agent
2018-11-08 10:16:30 - WARNING :: MainThread : Tautulli Libraries :: Unable to execute database query for get_sections: no such column: agent.
2018-11-08 10:16:30 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "C:\PlexTV\Tautulli-Tautulli-244008d\Tautulli.py", line 285, in <module>
    main()
  File "C:\PlexTV\Tautulli-Tautulli-244008d\Tautulli.py", line 214, in main
    plexpy.initialize(config_file)
  File "C:\PlexTV\Tautulli-Tautulli-244008d\plexpy\__init__.py", line 293, in initialize
    users.refresh_users()
  File "C:\PlexTV\Tautulli-Tautulli-244008d\plexpy\users.py", line 43, in refresh_users
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs])
TypeError: 'NoneType' object is not iterable

Traceback (most recent call last):
  File "C:\PlexTV\Tautulli-Tautulli-244008d\Tautulli.py", line 285, in <module>
    main()
  File "C:\PlexTV\Tautulli-Tautulli-244008d\Tautulli.py", line 214, in main
    plexpy.initialize(config_file)
  File "C:\PlexTV\Tautulli-Tautulli-244008d\plexpy\__init__.py", line 293, in initialize
    users.refresh_users()
  File "C:\PlexTV\Tautulli-Tautulli-244008d\plexpy\users.py", line 43, in refresh_users
    item['shared_libraries'] = ';'.join([str(l['section_id']) for l in libs])

I didn't do anything, I've just found those errors when trying to launch it :(

Can anybody help me out?
Thanks!

**Comment by BlackS0ull** [comment]
WOW ... actually the long answer in the FAQ in regards of this issue has helped me out to solve this issue.

Thank you so much guys for everything.

Now is working fine, so this issue can be considered CLOSED!!!
