### ISSUE TITLE
NOTIFICATION AGENTS - MQTT problem

### ISSUE THREAD

**Issue by emersonicus** [Tautulli/Tautulli-Issues#163]
Hi,

I have tautulli installed in unraid and its working fine except it has a problem with the mqtt settings. I set it in bridge or host mode but the result are the same. The problem with the agent is that if tautulli connected to the plex server, tautulli cannot connect and public the mqtt message and when plex server is offline tautulli can publish the mqtt message. How can I resolve this? 

thanks

```2019-02-24 19:13:17 - INFO :: CP Server Thread-9 : Tautulli Notifiers :: Updated notification agent: MQTT (notifier_id 1).
2019-02-24 19:13:21 - INFO :: CP Server Thread-9 : Tautulli Notifiers :: Updated notification agent: MQTT (notifier_id 1).
2019-02-24 19:13:21 - DEBUG :: CP Server Thread-9 : Sending test MQTT notification.
2019-02-24 19:13:21 - INFO :: Thread-2 : Tautulli NotificationHandler :: Preparing notification for notifier_id 1.
2019-02-24 19:13:24 - ERROR :: Thread-2 : Tautulli NotificationHandler :: Notification thread exception: [Errno 113] Host is unreachable

Traceback (most recent call last):
File "/app/tautulli/plexpy/notification_handler.py", line 58, in process_queue
notify(**params)
File "/app/tautulli/plexpy/notification_handler.py", line 369, in notify
**kwargs)
File "/app/tautulli/plexpy/notifiers.py", line 630, in send_notification
**kwargs)
File "/app/tautulli/plexpy/notifiers.py", line 810, in notify
return self.agent_notify(subject=subject, body=body, action=action, **kwargs)
File "/app/tautulli/plexpy/notifiers.py", line 2231, in agent_notify
keepalive=self.config['keep_alive'], auth=auth or None, protocol=self.config['protocol'])
File "/app/tautulli/lib/paho/mqtt/publish.py", line 216, in single
multiple([msg], hostname, port, client_id, keepalive, will, auth, tls, protocol)
File "/app/tautulli/lib/paho/mqtt/publish.py", line 169, in multiple
client.connect(hostname, port, keepalive)
File "/app/tautulli/lib/paho/mqtt/client.py", line 612, in connect
return self.reconnect()
File "/app/tautulli/lib/paho/mqtt/client.py", line 734, in reconnect
sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
File "/usr/lib/python2.7/socket.py", line 575, in create_connection
raise err
error: [Errno 113] Host is unreachable```

**Comment by samwiseg0** [comment]
Issues are not the place for support, as explained in the README. Please use one of the [support options](https://tautulli.com/#support) available, with Discord being preferred.
