### ISSUE TITLE
yet another database disk image malformed question

### ISSUE THREAD

**Issue by CRdeGraaf** [Tautulli/Tautulli-Issues#177]
After  ~900 days of running unattended on my plex server without issue i just lost all this precious viewing data in my install. Noticed after a few weeks that tautulli hasnt been running anymore. error: sqlite3.DatabaseError: database disk image is malformed
tried to follow https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q18
upon restoring tautulli booted but without any data.
all backups have been overwritten by now with this empty image of 20mb, which i suspect happened over the course of this week by looking at the timestamps.

I have no idea what the cause might have been as its been running unattended for 3 years other than the occasional windows 10 update and interested peek in viewer statistics. I switched computer systems but that was way before.
The server reboots every sundaynight and tautulli starts through task scheduler:
"C:\Python27\pythonw.exe" "D:\Program Files\Tautulli\PlexPy.py" running as local user, delayed by 2 minutes, repeated if fails.

i suspect on boot the backup is made before the integrity check, making the backups obsolete for people who dont look at tautulli daily. could this be the case? i wanted to point it out nonetheless as to me its seemingly coming out of nowhere.

pragma integrity check returns:
*** in database main ***
Main freelist: freelist leaf count too big on page 20839
On tree page 2 cell 1: overflow list length is 1 but should be 6
On tree page 4656 cell 1: 2nd reference to page 4657
Page 20743 is never used
Page 20766 is never used
Page 20799 is never used
Page 20819 is never used
Page 20824 is never used
Page 20838 is never used
Page 20840 is never used
Page 20841 is never used
Page 20843 is never used
Page 20845 is never used

full log:
https://gist.github.com/CRdeGraaf/36f6cf181eda0e3d6551e53953a2c169
there is about 5 more log files with the same errors within 5 days
just repeating these 4 lines:
ress, grandparent_thumb, video_framerate, transcode_hw_encoding, stream_video_decision, transcode_protocol, media_index, stream_video_height, stream_subtitle_decision, video_bitrate, synced_version_profile, original_title, stream_video_bitrate, session_id, live_uuid, stream_subtitle_codec, stopped, parent_thumb, stream_audio_codec, stream_audio_bitrate, grandparent_title, video_codec, parent_media_index, machine_id, width, audio_bitrate, session_key, rating_key) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) :: database disk image is malformed
2019-04-05 22:57:44 - ERROR   :: Thread-3 : Tautulli WebSocket :: Failed to process session data: database disk image is malformed.
2019-04-05 22:57:44 - DEBUG   :: Thread-3 : Tautulli ActivityHandler :: Session 5 started by user 17147185 (xxxxxx@xxxxxxxxx.xx) with ratingKey 97190 (Modern Family - A Sketchy Area).
2019-04-05 22:57:44 - ERROR   :: Thread-3 : Tautulli Database :: Fatal Error executing INSERT INTO sessions (stream_video_codec, transcode_width, stream_video_resolution, video_height, stream_video_width, friendly_name, year, subtitle_codec, height, stream_bitrate, player, optimized_version, parent_rating_key, audio_codec, parent_title, duration, session_key, subtitles, rating_key, transcode_video_codec, transcode_key, optimized_version_title, stream_audio_channels, user_id, thumb, title, bitrate, live, quality_profile, synced_version, transcode_audio_channels, video_decision, platform, state, transcode_height, transcode_container, transcode_hw_decoding, stream_video_framerate, media_type, video_resolution, grandparent_rating_key, stream_audio_decision, stream_container, transcode_audio_codec, product, audio_channels, view_offset, optimized_version_profile, section_id, stream_container_decision, aspect_ratio, full_title, user, raw_stream_info, audio_decision, transcode_decision, container, video_width, ip_add

on manual execute:

D:\Program Files\Tautulli>python tautulli.py
2019-05-15 11:19:55 - INFO :: MainThread : Starting Tautulli v2.1.22
2019-05-15 11:19:55 - INFO :: MainThread : Windows 10 (10.0.17134)
2019-05-15 11:19:55 - INFO :: MainThread : Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
2019-05-15 11:19:55 - INFO :: MainThread : Program Dir: D:\Program Files\Tautulli
2019-05-15 11:19:55 - INFO :: MainThread : Config File: D:\Program Files\Tautulli\config.ini
2019-05-15 11:19:55 - INFO :: MainThread : Database File: D:\Program Files\Tautulli\tautulli.db
2019-05-15 11:19:55 - INFO :: MainThread : Checking if the database upgrades are required...
2019-05-15 11:19:55 - INFO :: MainThread : Checking if configuration upgrades are required...
2019-05-15 11:19:55 - INFO :: MainThread : Retrieving latest version information from GitHub
2019-05-15 11:19:55 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/Tautulli/Tautulli/commits/master
2019-05-15 11:19:56 - DEBUG :: MainThread : Latest version is 2635569e765e5817400ed1032a27bfc850242f6a
2019-05-15 11:19:56 - INFO :: MainThread : Comparing currently installed version with latest GitHub version
2019-05-15 11:19:56 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/Tautulli/Tautulli/compare/2635569e765e5817400ed1032a27bfc850242f6a...None
2019-05-15 11:19:57 - INFO :: MainThread : Cannot compare versions. Are you running a local development version?
2019-05-15 11:19:57 - INFO :: MainThread : Tautulli is up to date
2019-05-15 11:19:57 - INFO :: MainThread : Tautulli PlexTV :: Requesting resources for server...
2019-05-15 11:19:58 - INFO :: MainThread : Tautulli PlexTV :: Server URL retrieved.
2019-05-15 11:19:58 - INFO :: MainThread : Tautulli Config :: Writing configuration to file
2019-05-15 11:19:58 - INFO :: MainThread : Tautulli Users :: Requesting users list refresh...
2019-05-15 11:19:59 - ERROR :: MainThread : Tautulli Database :: Fatal Error executing INSERT INTO users (username, filter_movies, is_admin, server_token, filter_music, custom_avatar_url, thumb, shared_libraries, filter_all, is_allow_sync, filter_photos, filter_tv, is_restricted, is_home_user, email, user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) :: database disk image is malformed
2019-05-15 11:19:59 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "tautulli.py", line 271, in <module>
    main()
  File "tautulli.py", line 200, in main
    plexpy.initialize(config_file)
  File "D:\Program Files\Tautulli\plexpy\__init__.py", line 287, in initialize
    users.refresh_users()
  File "D:\Program Files\Tautulli\plexpy\users.py", line 59, in refresh_users
    monitor_db.upsert('users', item, keys_dict)
  File "D:\Program Files\Tautulli\plexpy\database.py", line 200, in upsert
    self.action(insert_query, value_dict.values() + key_dict.values())
  File "D:\Program Files\Tautulli\plexpy\database.py", line 144, in action
    sql_result = c.execute(query, args)
DatabaseError: database disk image is malformed

Traceback (most recent call last):
  File "tautulli.py", line 271, in <module>
    main()
  File "tautulli.py", line 200, in main
    plexpy.initialize(config_file)
  File "D:\Program Files\Tautulli\plexpy\__init__.py", line 287, in initialize
    users.refresh_users()
  File "D:\Program Files\Tautulli\plexpy\users.py", line 59, in refresh_users
    monitor_db.upsert('users', item, keys_dict)
  File "D:\Program Files\Tautulli\plexpy\database.py", line 200, in upsert
    self.action(insert_query, value_dict.values() + key_dict.values())
  File "D:\Program Files\Tautulli\plexpy\database.py", line 144, in action
    sql_result = c.execute(query, args)
sqlite3.DatabaseError: database disk image is malformed

D:\Program Files\Tautulli>

**Version:**
 Tautulli v2.1.22
**Branch:**

**Commit hash:**

**Operating system:**
Windows 10 (10.0.17134)

**Python version:**
Python 2.7.15 
**What you did?**
auto start through task scheduler
**What happened?**
sqlite3.DatabaseError: database disk image is malformed
**What you expected?**
it to boot with my viewing data in tact
**How can we reproduce your issue?**
i wouldnt know how, i can share the broken db backups?

**What are your (relevant) settings?**
[IFTTT]
ifttt_on_stop = 0
ifttt_on_pause = 0
ifttt_key = ""
ifttt_on_concurrent = 0
ifttt_on_created = 0
ifttt_on_buffer = 0
ifttt_enabled = 0
ifttt_on_pmsupdate = 0
ifttt_on_newdevice = 0
ifttt_on_intdown = 0
ifttt_on_extup = 0
ifttt_on_intup = 0
ifttt_on_resume = 0
ifttt_on_watched = 0
ifttt_event = tautulli
ifttt_on_extdown = 0
ifttt_on_play = 0
[Growl]
growl_enabled = 0
growl_on_play = 0
growl_on_stop = 0
growl_on_buffer = 0
growl_on_pause = 0
growl_on_intdown = 0
growl_host = ""
growl_on_extup = 0
growl_on_newdevice = 0
growl_on_pmsupdate = 0
growl_password = ""
growl_on_resume = 0
growl_on_created = 0
growl_on_concurrent = 0
growl_on_watched = 0
growl_on_intup = 0
growl_on_extdown = 0
[PMS]
pms_use_bif = 0
pms_uuid = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
pms_url_manual = 0
pms_web_url = https://app.plex.tv/desktop
pms_url = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
pms_update_channel = plex
pms_update_distro = english
pms_name = CR Server
pms_logs_folder = ""
pms_plexpass = 1
pms_token = xxxxxxxxxxxxxxxxxxx
pms_url_override = ""
pms_port = 32400
pms_is_remote = 0
pms_identifier = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
pms_ssl = 1
pms_version = 1.15.4.993-bb4a2cb6c
pms_update_distro_build = windows-i386
pms_ip = 10.0.0.201
pms_logs_line_cap = 1000
pms_platform = Windows
pms_is_cloud = 0
[Monitoring]
notify_upload_posters = 0
movie_notify_enable = 0
notify_on_resume_body_text = {user} ({player}) has resumed {title}.
notify_on_pmsupdate_body_text = An update is available for the Plex Media Server (version {update_version}).
refresh_libraries_on_startup = 1
notify_on_created_body_text = {title} was recently added to Plex.
buffer_wait = 900
notify_on_intup_subject_text = Tautulli ({server_name})
notify_concurrent_by_ip = 0
notify_on_newdevice_subject_text = Tautulli ({server_name})
notify_on_extup_subject_text = Tautulli ({server_name})
notify_on_watched_subject_text = Tautulli ({server_name})
notify_on_pause_subject_text = Tautulli ({server_name})
notify_on_extup_body_text = The Plex Media Server remote access is back up.
tv_watched_percent = 85
notify_on_watched_body_text = {user} ({player}) has watched {title}.
music_notify_on_pause = 0
notify_group_recently_added_grandparent = 0
notify_on_start_body_text = {user} ({player}) started playing {title}.
notify_on_pause_body_text = {user} ({player}) has paused {title}.
notify_on_buffer_body_text = {user} ({player}) is buffering {title}.
music_notify_on_stop = 0
notify_recently_added_upgrade = 0
tv_notify_on_stop = 0
notify_on_stop_body_text = {user} ({player}) has stopped {title}.
notify_on_created_subject_text = Tautulli ({server_name})
notify_on_extdown_body_text = The Plex Media Server remote access is down.
notify_scripts_args_text = ""
music_logging_enable = 1
movie_notify_on_stop = 0
notify_watched_percent = 85
notify_group_recently_added = 0
notify_on_concurrent_subject_text = Tautulli ({server_name})
notify_on_concurrent_body_text = {user} has {user_streams} concurrent streams.
tv_logging_enable = 1
notify_group_recently_added_parent = 0
tv_notify_enable = 0
notify_recently_added_delay = 60
notify_on_intdown_body_text = The Plex Media Server is down.
video_logging_enable = 1
logging_ignore_interval = 120
notify_on_newdevice_body_text = {user} is streaming from a new device: {player}.
refresh_users_interval = 12
monitoring_use_websocket = 1
monitor_pms_updates = 0
notify_on_start_subject_text = Tautulli ({server_name})
notify_recently_added = 0
notify_on_pmsupdate_subject_text = Tautulli ({server_name})
music_notify_enable = 0
movie_notify_on_start = 1
refresh_users_on_startup = 1
buffer_threshold = 3
notify_on_extdown_subject_text = Tautulli ({server_name})
refresh_libraries_interval = 12
tv_notify_on_start = 1
notify_recently_added_grandparent = 0
notify_on_resume_subject_text = Tautulli ({server_name})
notify_concurrent_threshold = 2
notify_on_stop_subject_text = Tautulli ({server_name})
movie_notify_on_pause = 0
notify_consecutive = 0
movie_logging_enable = 1
notify_on_intup_body_text = The Plex Media Server is back up.
notify_on_intdown_subject_text = Tautulli ({server_name})
music_notify_on_start = 1
tv_notify_on_pause = 0
monitor_remote_access = 0
imgur_client_id = ""
movie_watched_percent = 85
monitoring_interval = 60
music_watched_percent = 85
notify_on_buffer_subject_text = Tautulli ({server_name})
[General]
week_start_monday = 0
git_token = ""
home_stats_cards = top_movies, popular_movies, top_tv, popular_tv, top_music, popular_music, last_watched, top_users, top_platforms, most_concurrent
backup_interval = 6
graph_days = 1000
graph_type = duration
http_plex_admin = 0
get_file_sizes = 0
http_basic_auth = 0
api_sql = 0
update_show_changelog = 0
http_root = ""
http_proxy = 0
freeze_db = 0
show_advanced_settings = 0
ip_logging_enable = 0
launch_browser = 0
http_username = ""
git_remote = origin
https_create_cert = 0
do_not_override_git_branch = 0
home_stats_length = 900
http_host = 0.0.0.0
https_cert_chain = ""
first_run_complete = 1
git_repo = Tautulli
home_stats_recently_added_count = 50
enable_https = 0
check_github = 1
api_enabled = 1
git_path = ""
themoviedb_apikey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
tvmaze_lookup = 0
check_github_interval = 360
https_ip = 127.0.0.1
update_notifiers_db = 0
group_history_tables = 1
https_domain = localhost
graph_tab = tabs-1
geoip_db = ""
http_password = ""
home_stats_count = 5
backup_dir = D:\Program Files\Tautulli\backups
git_user = Tautulli
interface = default
cache_images = 1
log_blacklist = 1
graph_months = 12
themoviedb_lookup = 0
cleanup_files = 0
plexpy_auto_update = 0
check_github_on_startup = 1
http_port = 18295
log_dir = D:\Program Files\Tautulli\logs
update_db_interval = 24
allow_guest_access = 0
time_format = HH:mm
cache_dir = D:\Program Files\Tautulli\cache
home_sections = current_activity, watch_stats, library_stats, recently_added
backup_days = 3
https_cert = D:\Program Files\Tautulli\server.crt
home_refresh_interval = 10
api_key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
win_sys_tray = 1
update_section_ids = 1
date_format = YYYY-MM-DD
update_labels = 1
home_stats_type = 0
update_libraries_db_notify = 0
http_environment = production
history_table_activity = 1
http_base_url = ""
https_key = D:\Program Files\Tautulli\server.key
http_hash_password = 0
home_library_cards = 6, 10, 14, 15, 1, 16, 16, 6, 10, 14, 15, 1
http_hashed_password = 0
git_branch = master
anon_redirect = https://www.nullrefer.com/?
[[get_file_sizes_hold]]
section_ids = ,
rating_keys = ,
[Slack]
slack_on_stop = 0
slack_on_watched = 0
slack_on_extup = 0
slack_on_resume = 0
slack_hook = ""
slack_incl_subject = 1
slack_on_pmsupdate = 0
slack_channel = ""
slack_on_buffer = 0
slack_on_extdown = 0
slack_username = ""
slack_incl_pmslink = 0
slack_enabled = 0
slack_incl_poster = 0
slack_on_pause = 0
slack_on_concurrent = 0
slack_on_intup = 0
slack_on_intdown = 0
slack_on_created = 0
slack_on_play = 0
slack_on_newdevice = 0
slack_icon_emoji = ""
[Boxcar]
boxcar_sound = ""
boxcar_on_newdevice = 0
boxcar_on_watched = 0
boxcar_on_buffer = 0
boxcar_on_stop = 0
boxcar_on_extdown = 0
boxcar_on_pmsupdate = 0
boxcar_on_intdown = 0
boxcar_on_pause = 0
boxcar_on_play = 0
boxcar_on_created = 0
boxcar_on_intup = 0
boxcar_on_resume = 0
boxcar_on_concurrent = 0
boxcar_enabled = 0
boxcar_on_extup = 0
boxcar_token = ""
[PushBullet]
pushbullet_on_play = 0
pushbullet_channel_tag = ""
pushbullet_on_pmsupdate = 0
pushbullet_on_buffer = 0
pushbullet_apikey = ""
pushbullet_on_resume = 0
pushbullet_on_concurrent = 0
pushbullet_on_created = 0
pushbullet_on_pause = 0
pushbullet_on_extdown = 0
pushbullet_on_stop = 0
pushbullet_on_extup = 0
pushbullet_enabled = 0
pushbullet_on_watched = 0
pushbullet_on_intdown = 0
pushbullet_deviceid = ""
pushbullet_on_intup = 0
pushbullet_on_newdevice = 0
[Scripts]
scripts_on_newdevice = 0
scripts_on_extdown_script = ""
scripts_on_intup_script = ""
scripts_on_stop = 0
scripts_on_intdown_script = ""
scripts_on_intdown = 0
scripts_on_newdevice_script = ""
scripts_folder = ""
scripts_on_pmsupdate = 0
scripts_on_buffer = 0
scripts_on_concurrent = 0
scripts_on_resume = 0
scripts_on_extup = 0
scripts_on_play_script = ""
scripts_on_created_script = ""
scripts_on_pmsupdate_script = ""
scripts_on_resume_script = ""
scripts_on_stop_script = ""
scripts_on_watched_script = ""
scripts_enabled = 0
scripts_on_extup_script = ""
scripts_on_extdown = 0
scripts_on_created = 0
scripts_on_concurrent_script = ""
scripts_on_pause_script = ""
scripts_on_pause = 0
scripts_on_intup = 0
scripts_timeout = 30
scripts_on_watched = 0
scripts_on_buffer_script = ""
scripts_on_play = 0
[OSX_Notify]
osx_notify_on_pause = 0
osx_notify_on_intdown = 0
osx_notify_on_buffer = 0
osx_notify_app = /Applications/Tautulli
osx_notify_on_created = 0
osx_notify_on_pmsupdate = 0
osx_notify_on_stop = 0
osx_notify_enabled = 0
osx_notify_on_intup = 0
osx_notify_on_watched = 0
osx_notify_on_concurrent = 0
osx_notify_on_newdevice = 0
osx_notify_on_play = 0
osx_notify_on_extdown = 0
osx_notify_on_extup = 0
osx_notify_on_resume = 0
[NMA]
nma_on_pmsupdate = 0
nma_priority = 0
nma_on_intdown = 0
nma_on_buffer = 0
nma_on_play = 0
nma_on_newdevice = 0
nma_on_concurrent = 0
nma_on_resume = 0
nma_on_watched = 0
nma_apikey = ""
nma_on_intup = 0
nma_on_stop = 0
nma_on_created = 0
nma_on_pause = 0
nma_enabled = 0
nma_on_extdown = 0
nma_on_extup = 0
[Hipchat]
hipchat_emoticon = ""
hipchat_incl_subject = 1
hipchat_on_extdown = 0
hipchat_on_intup = 0
hipchat_enabled = 0
hipchat_on_created = 0
hipchat_on_newdevice = 0
hipchat_on_play = 0
hipchat_on_resume = 0
hipchat_on_buffer = 0
hipchat_incl_poster = 0
hipchat_on_watched = 0
hipchat_color = ""
hipchat_on_concurrent = 0
hipchat_url = ""
hipchat_on_pmsupdate = 0
hipchat_on_extup = 0
hipchat_incl_pmslink = 0
hipchat_on_pause = 0
hipchat_on_intdown = 0
hipchat_on_stop = 0
[Pushalot]
pushalot_apikey = ""
pushalot_on_pmsupdate = 0
pushalot_enabled = 0
pushalot_on_extdown = 0
pushalot_on_created = 0
pushalot_on_pause = 0
pushalot_on_stop = 0
pushalot_on_buffer = 0
pushalot_on_intup = 0
pushalot_on_concurrent = 0
pushalot_on_newdevice = 0
pushalot_on_watched = 0
pushalot_on_play = 0
pushalot_on_extup = 0
pushalot_on_intdown = 0
pushalot_on_resume = 0
[Prowl]
prowl_on_created = 0
prowl_on_play = 0
prowl_on_extdown = 0
prowl_on_pause = 0
prowl_on_intdown = 0
prowl_on_intup = 0
prowl_enabled = 0
prowl_priority = 0
prowl_on_pmsupdate = 0
prowl_on_newdevice = 0
prowl_on_extup = 0
prowl_on_watched = 0
prowl_on_buffer = 0
prowl_on_resume = 0
prowl_on_stop = 0
prowl_on_concurrent = 0
prowl_keys = ""
[Advanced]
verify_ssl_cert = 1
session_db_write_attempts = 5
system_analytics = 1
journal_mode = wal
notification_threads = 2
remote_access_ping_threshold = 3
websocket_connection_timeout = 5
config_version = 11
metadata_cache_seconds = 1800
pms_timeout = 15
websocket_monitor_ping_pong = 0
websocket_connection_attempts = 5
jwt_secret = xxxxxxxxxxxxxxxxxxxxxxxxxxxx
cache_sizemb = 32
[Facebook]
facebook_app_secret = ""
facebook_on_stop = 0
facebook_token = ""
facebook_on_buffer = 0
facebook_on_play = 0
facebook_enabled = 0
facebook_on_intup = 0
facebook_incl_poster = 0
facebook_on_pmsupdate = 0
facebook_on_intdown = 0
facebook_on_extup = 0
facebook_on_resume = 0
facebook_on_concurrent = 0
facebook_on_extdown = 0
facebook_group = ""
facebook_on_pause = 0
facebook_app_id = ""
facebook_incl_pmslink = 0
facebook_on_newdevice = 0
facebook_on_watched = 0
facebook_redirect_uri = ""
facebook_incl_subject = 1
facebook_on_created = 0
[Email]
email_from_name = Tautulli
email_bcc = ""
email_on_pause = 0
email_smtp_password = ""
email_tls = 0
email_smtp_port = 25
email_on_watched = 0
email_smtp_server = ""
email_on_intdown = 0
email_on_concurrent = 0
email_on_intup = 0
email_enabled = 0
email_on_buffer = 0
email_on_resume = 0
email_smtp_user = ""
email_cc = ""
email_on_newdevice = 0
email_on_stop = 0
email_on_extdown = 0
email_html_support = 1
email_on_extup = 0
email_on_created = 0
email_on_pmsupdate = 0
email_to = ""
email_from = ""
email_on_play = 0
[PlexWatch]
grouping_user_history = 0
plexwatch_database = ""
grouping_global_history = 0
grouping_charts = 0
[Pushover]
pushover_enabled = 0
pushover_on_extup = 0
pushover_on_intup = 0
pushover_on_buffer = 0
pushover_html_support = 1
pushover_keys = ""
pushover_incl_url = 1
pushover_on_pause = 0
pushover_on_play = 0
pushover_on_stop = 0
pushover_apitoken = ""
pushover_incl_pmslink = 0
pushover_on_pmsupdate = 0
pushover_on_extdown = 0
pushover_priority = 0
pushover_on_intdown = 0
pushover_on_newdevice = 0
pushover_sound = ""
pushover_on_created = 0
pushover_on_resume = 0
pushover_on_concurrent = 0
pushover_on_watched = 0
[Telegram]
telegram_on_buffer = 0
telegram_bot_token = ""
telegram_incl_poster = 0
telegram_on_resume = 0
telegram_on_pmsupdate = 0
telegram_html_support = 1
telegram_incl_subject = 1
telegram_disable_web_preview = 0
telegram_enabled = 0
telegram_on_concurrent = 0
telegram_on_intdown = 0
telegram_on_extdown = 0
telegram_on_pause = 0
telegram_on_newdevice = 0
telegram_on_watched = 0
telegram_on_stop = 0
telegram_on_play = 0
telegram_on_created = 0
telegram_on_extup = 0
telegram_chat_id = ""
telegram_on_intup = 0
[Twitter]
twitter_on_resume = 0
twitter_on_pmsupdate = 0
twitter_on_buffer = 0
twitter_on_concurrent = 0
twitter_enabled = 0
twitter_on_watched = 0
twitter_access_token = ""
twitter_consumer_secret = ""
twitter_on_extup = 0
twitter_on_intdown = 0
twitter_on_intup = 0
twitter_access_token_secret = ""
twitter_on_newdevice = 0
twitter_on_stop = 0
twitter_consumer_key = ""
twitter_incl_subject = 1
twitter_on_extdown = 0
twitter_incl_poster = 0
twitter_on_pause = 0
twitter_on_play = 0
twitter_on_created = 0
[Plex]
plex_on_created = 0
plex_on_concurrent = 0
plex_client_host = ""
plex_on_stop = 0
plex_on_resume = 0
plex_on_watched = 0
plex_on_play = 0
plex_on_extdown = 0
plex_on_intdown = 0
plex_on_newdevice = 0
plex_enabled = 0
plex_on_buffer = 0
plex_on_intup = 0
plex_on_pmsupdate = 0
plex_username = ""
plex_on_pause = 0
plex_password = ""
plex_on_extup = 0
[Join]
join_on_concurrent = 0
join_on_newdevice = 0
join_deviceid = ""
join_on_play = 0
join_on_watched = 0
join_on_resume = 0
join_on_created = 0
join_on_extdown = 0
join_on_intup = 0
join_on_buffer = 0
join_incl_subject = 1
join_enabled = 0
join_on_pause = 0
join_apikey = ""
join_on_pmsupdate = 0
join_on_intdown = 0
join_on_extup = 0
join_on_stop = 0
[XBMC]
xbmc_password = ""
xbmc_on_play = 0
xbmc_on_pause = 0
xbmc_username = ""
xbmc_on_extup = 0
xbmc_on_watched = 0
xbmc_on_buffer = 0
xbmc_enabled = 0
xbmc_host = ""
xbmc_on_created = 0
xbmc_on_intup = 0
xbmc_on_extdown = 0
xbmc_on_pmsupdate = 0
xbmc_on_stop = 0
xbmc_on_newdevice = 0
xbmc_on_resume = 0
xbmc_on_intdown = 0
xbmc_on_concurrent = 0
[Newsletter]
newsletter_dir = D:\Program Files\Tautulli\newsletters
newsletter_static_url = 0
newsletter_templates = newsletters
newsletter_self_hosted = 0
newsletter_inline_styles = 0
newsletter_password = ""
newsletter_custom_dir = ""
newsletter_auth = 0
[Browser]
browser_on_intdown = 0
browser_on_newdevice = 0
browser_on_pmsupdate = 0
browser_on_intup = 0
browser_on_buffer = 0
browser_auto_hide_delay = 5
browser_on_created = 0
browser_on_pause = 0
browser_on_stop = 0
browser_on_play = 0
browser_on_watched = 0
browser_on_extdown = 0
browser_on_extup = 0
browser_on_resume = 0
browser_on_concurrent = 0
browser_enabled = 0
[Cloudinary]
cloudinary_api_key = ""
cloudinary_cloud_name = ""
cloudinary_api_secret = ""

**Link to logs:**
https://gist.github.com/CRdeGraaf/36f6cf181eda0e3d6551e53953a2c169

**Comment by CRdeGraaf** [comment]
my thought process was wrong. the database showed empty after multiple tries to restore it. db browser for sqlite didnt show anything and when export-importing the file into a new db tautulli also didnt show my data.
i used another tool (sqlite forensic browser). and for some reason that tool does show the tables. it costs money so im looking for a tool to do it for free before comitting to it. but at least the data is not gone. just corrupted :)
