### ISSUE TITLE
Error send newsletter

### ISSUE THREAD

**Issue by jamesdotbond** [Tautulli/Tautulli-Issues#302]
Version v2.6.6

Error:
Tautulli NotificationHandler :: Notification thread exception: please run connect() first
Traceback (most recent call last):
    File "/opt/Tautulli/plexpy/notification_handler.py", line 77, in process_queue
        notify_newsletter(**params)
    File "/opt/Tautulli/plexpy/newsletter_handler.py", line 137, in notify
        success = newsletter_agent.send()
    File "/opt/Tautulli/plexpy/newsletters.py", line 527, in send
        return self._send()
    File "/opt/Tautulli/plexpy/newsletters.py", line 577, in _send
        reply_msg_id=email_reply_msg_id
    File "/opt/Tautulli/plexpy/notifiers.py", line 842, in notify
        return self.agent_notify(subject=subject, body=body, action=action, **kwargs)
    File "/opt/Tautulli/plexpy/notifiers.py", line 1417, in agent_notify
        mailserver.quit()
    File "/usr/lib/python3.7/smtplib.py", line 984, in quit
        res = self.docmd("quit")
    File "/usr/lib/python3.7/smtplib.py", line 420, in docmd
        self.putcmd(cmd, args)
    File "/usr/lib/python3.7/smtplib.py", line 367, in putcmd
        self.send(str)
    File "/usr/lib/python3.7/smtplib.py", line 359, in send
        raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

**Comment by samwiseg0** [comment]
Issues is not the place for support. Please use one of the [support options](https://tautulli.com/#support), with Discord being preferred.

**Comment by jamesdotbond** [comment]
Simple error ... have to fill the entire template?

**Comment by samwiseg0** [comment]
> Simple error ... have to fill the entire template?

Yes you would have if it was a bug. Again this is not the place for support. See my first comment
