### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by mutluerol** [Tautulli/Tautulli-Issues#67]
400 Bad Request

Illegal cookie name ys-torrentGrid

Traceback (most recent call last):
  File "/opt/Tautulli/lib/cherrypy/_cprequest.py", line 635, in respond
    self.process_headers()
  File "/opt/Tautulli/lib/cherrypy/_cprequest.py", line 737, in process_headers
    raise cherrypy.HTTPError(400, msg)
HTTPError: (400, 'Illegal cookie name ys-torrentGrid')

i am using nightly version, 
python2.7
gentoo

**Comment by JonnyWong16** [comment]
Not a bug report.

Clear your browser cache.
