### ISSUE TITLE
Cannot create Newsletter unless Public Tautulli Domain is set even if Self-Hosted Newsletters is disabled

### ISSUE THREAD

**Issue by ridizy** [Tautulli/Tautulli-Issues#68]
**Version:** V2.1.2-BETA

**Branch:** beta

**Commit hash:** e9676e365110ca11a44ff8f5d39ea2e7598f7cc7

**Operating system:** Darwin 17.5.0

**Python version:** 2.7.10 (default, Oct 6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

**What you did?**
- Go to `Settings | Newsletter Agents`
- Click on `Add a new newsletter agent`
- Click on `Recently Added`

**What happened?**
Nothing

**What you expected?**
A new Newsletter Agent would be added

**How can we reproduce your issue?**
Follow the steps above with `Settings | Web Interface | Public Tautulli Domain` blank 

**Log** https://gist.github.com/ridizy/66eb4e89833cca339971549b14a54a31

**Note**
I may have missed this in the documentation or FAQ, but in the UI, there is no indication that `Public Tautulli Domain` must be set to use newsletters

**Comment by JonnyWong16** [comment]
Try clearing your browser cache?

**Comment by ridizy** [comment]
My first thought was a browser issue as well, but it happens on multiple browsers.

Also, after setting `Public Tautulli Domain` to something (doesn't have to work), I can create a newsletter.  If I go back in and clear `Public Tautulli Domain`, it reverts to the previous behavior where nothing happens and no feedback is provided.

**Comment by JonnyWong16** [comment]
Logs please, as per the guidelines in the issues template.

```
  * Include a link to your **FULL** log file that has the error(not just a few lines!).
    Please use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com/).
```

**Comment by ridizy** [comment]
Added link to logs in initial issue.

2018-05-01 19:14:38 --> I clicked on `Recently Added` 3x with `Public Tautulli Domain` blank and nothing happened
2018-05-01 19:15:39 --> I added a `Public Tautulli Domain`
2018-05-01 19:15:45  --> I successfully created a new Newsletter Agent

**Comment by JonnyWong16** [comment]
Can you start Tautulli in dev mode with `python Tautulli.py --dev`, then go to
```
https://localhost:8181/add_newsletter_config?agent_id=0
```
and post the error message?

**Comment by ridizy** [comment]
Sure.

```
Traceback (most recent call last):
  File "lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "lib/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/Applications/PlexPy/plexpy/helpers.py", line 65, in wrapper
    return function(*args, **kwargs)
  File "/Applications/PlexPy/plexpy/webserve.py", line 5565, in add_newsletter_config
    result = newsletters.add_newsletter_config(agent_id=agent_id, **kwargs)
  File "/Applications/PlexPy/plexpy/newsletters.py", line 173, in add_newsletter_config
    agent_class = get_agent_class(agent_id=agent['id'])
  File "/Applications/PlexPy/plexpy/newsletters.py", line 80, in get_agent_class
    return RecentlyAdded(**kwargs)
  File "/Applications/PlexPy/plexpy/newsletters.py", line 345, in __init__
    self.parameters = self.build_params()
  File "/Applications/PlexPy/plexpy/newsletters.py", line 774, in build_params
    parameters = self._build_params()
  File "/Applications/PlexPy/plexpy/newsletters.py", line 478, in _build_params
    base_url = plexpy.CONFIG.HTTP_BASE_URL or helpers.get_plexpy_url()
  File "/Applications/PlexPy/plexpy/helpers.py", line 1075, in get_plexpy_url
    hostname = socket.gethostbyname(socket.gethostname())
gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by JonnyWong16** [comment]
https://stackoverflow.com/questions/39970606/gaierror-errno-8-nodename-nor-servname-provided-or-not-known-with-macos-sie

**Comment by ridizy** [comment]
Thanks.  After adding the FQDN for my `$HOSTNAME` to the loopback address in `/etc/hosts`, it works with `Public Tautulli Domain` blank.
