### ISSUE TITLE
Unable to start application on Mac OSX 10.13.5

### ISSUE THREAD

**Issue by sumnercreations** [Tautulli/Tautulli-Issues#88]
**Version:**
2.1.9

**Branch:**
v2.1.9 (also happens on master)

**Commit hash:**
8e4aba7

**Operating system:**
Mac OSX

**Python version:**
2.7.10

**What you did?**
Started the service
`python Tautulli.py`

**What happened?**
Errors in the terminal window appeared.

**What you expected?**
The service / application would start up

**How can we reproduce your issue?**
1. Update Mac OS X to 10.13.5
2. cd into the folder where you have the cloned the code
3. run the command to start it `python Tautulli.py`

**What are your (relevant) settings?**

**Link to logs:**
(this is the whole log on terminal)
```
python Tautulli.py
2018-06-03 17:04:15 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "Tautulli.py", line 267, in <module>
    main()
  File "Tautulli.py", line 200, in main
    plexpy.initialize(config_file)
  File "/Applications/Tautulli/plexpy/__init__.py", line 120, in initialize
    CONFIG = plexpy.config.Config(config_file)
  File "/Applications/Tautulli/plexpy/config.py", line 683, in __init__
    self._config = ConfigObj(self._config_file, encoding='utf-8')
  File "lib/configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "lib/configobj.py", line 1332, in _load
    raise error
ParseError: Invalid line at line "479".

Traceback (most recent call last):
  File "Tautulli.py", line 267, in <module>
    main()
  File "Tautulli.py", line 200, in main
    plexpy.initialize(config_file)
  File "/Applications/Tautulli/plexpy/__init__.py", line 120, in initialize
    CONFIG = plexpy.config.Config(config_file)
  File "/Applications/Tautulli/plexpy/config.py", line 683, in __init__
    self._config = ConfigObj(self._config_file, encoding='utf-8')
  File "lib/configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "lib/configobj.py", line 1332, in _load
    raise error
configobj.ParseError: Invalid line at line "479".
```

**Comment by Arcanemagus** [comment]
https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q20

**Comment by sumnercreations** [comment]
@Arcanemagus how do I restore config.ini from the backups folder? It looks like it's just a whole backup of the database.

**Comment by sumnercreations** [comment]
@Arcanemagus never mind, I see it now. There are .ini files and .db files. I was grabbing the wrong one... sorry.
