### ISSUE TITLE
Tautilli crashed last night. Wont start back up

### ISSUE THREAD

**Issue by ghost** [Tautulli/Tautulli-Issues#91]
**Version:**

**Branch:**
MAster
**Commit hash:**

**Operating system:**
MacOS

**Python version:**
2.7
**What you did?**
Nothing at all. It lost connection for some reason last night,. It wont come back up this morning. I tried rebooting, I tried manually running the script. I get this error:

2018-06-11 08:27:59 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
  File "plexpy.py", line 28, in <module>
    main()
  File "/Applications/Tautulli/Tautulli.py", line 200, in main
    plexpy.initialize(config_file)
  File "/Applications/Tautulli/plexpy/__init__.py", line 120, in initialize
    CONFIG = plexpy.config.Config(config_file)
  File "/Applications/Tautulli/plexpy/config.py", line 683, in __init__
    self._config = ConfigObj(self._config_file, encoding='utf-8')
  File "/Applications/Tautulli/lib/configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "/Applications/Tautulli/lib/configobj.py", line 1332, in _load
    raise error
ParseError: Invalid line at line "294".

Traceback (most recent call last):
  File "plexpy.py", line 28, in <module>
    main()
  File "/Applications/Tautulli/Tautulli.py", line 200, in main
    plexpy.initialize(config_file)
  File "/Applications/Tautulli/plexpy/__init__.py", line 120, in initialize
    CONFIG = plexpy.config.Config(config_file)
  File "/Applications/Tautulli/plexpy/config.py", line 683, in __init__
    self._config = ConfigObj(self._config_file, encoding='utf-8')
  File "/Applications/Tautulli/lib/configobj.py", line 1242, in __init__
    self._load(infile, configspec)
  File "/Applications/Tautulli/lib/configobj.py", line 1332, in _load
    raise error
configobj.ParseError: Invalid line at line "294".

**What happened?**
Could access Tautilli last night. This morning 

**What you expected?**
Service would come back up after a reboot, or when I start it manually

**How can we reproduce your issue?**
I am not sure how to reproduce it myself

**What are your (relevant) settings?**

**Link to logs:**
This was the last thin that happened last night. It lost connection to Plex for some reason.

2018-06-11 02:38:24 - INFO    :: Thread-1 : Tautulli Notifiers :: Slack notification sent.
2018-06-11 02:43:04 - INFO    :: Thread-15 : Tautulli Config :: Writing configuration to file
2018-06-11 02:43:04 - DEBUG   :: Thread-15 : Tautulli Config :: Successfully backed up /Applications/Tautulli/config.ini to config.backup-20180611024304.sched.ini
2018-06-11 02:43:04 - DEBUG   :: Thread-37 : Tautulli Database :: Successfully backed up /Applications/Tautulli/tautulli.db to tautulli.backup-20180611024304.sched.db
2018-06-11 03:10:00 - WARNING :: Thread-45 : Tautulli WebSocket :: Connection has closed.
2018-06-11 03:10:00 - WARNING :: Thread-45 : Tautulli WebSocket :: Reconnection attempt 1.
2018-06-11 03:10:00 - ERROR   :: Thread-45 : Tautulli WebSocket :: [Errno 61] Connection refused.
2018-06-11 03:10:05 - WARNING :: Thread-45 : Tautulli WebSocket :: Reconnection attempt 2.
2018-06-11 03:10:05 - ERROR   :: Thread-45 : Tautulli WebSocket :: [Errno 61] Connection refused.
2018-06-11 03:10:10 - WARNING :: Thread-45 : Tautulli WebSocket :: Reconnection attempt 3.
2018-06-11 03:10:10 - ERROR   :: Thread-45 : Tautulli WebSocket :: [Errno 61] Connection refused.
2018-06-11 03:10:15 - WARNING :: Thread-45 : Tautulli WebSocket :: Reconnection attempt 4.
2018-06-11 03:10:15 - ERROR   :: Thread-45 : Tautulli WebSocket :: [Errno 61] Connection refused.
2018-06-11 03:10:20 - WARNING :: Thread-45 : Tautulli WebSocket :: Reconnection attempt 5.
2018-06-11 03:10:20 - ERROR   :: Thread-45 : Tautulli WebSocket :: [Errno 61] Connection refused.
2018-06-11 03:10:20 - INFO    :: Thread-45 : Tautulli WebSocket :: Disconnecting websocket...
2018-06-11 03:10:20 - INFO    :: Thread-45 : Tautulli WebSocket :: Unable to get a response from the server, Plex server is down.
2018-06-11 03:10:21 - INFO    :: Thread-45 : Removed background task: Refresh Plex server URLs
2018-06-11 03:10:21 - INFO    :: Thread-45 : Removed background task: Refresh users list
2018-06-11 03:10:21 - INFO    :: Thread-45 : Removed background task: Refresh libraries list
2018-06-11 03:10:21 - INFO    :: Thread-45 : Scheduled background task: Check for server response
2018-06-11 03:10:21 - DEBUG   :: Thread-45 : Tautulli WebSocket :: Leaving thread.
2018-06-11 03:10:21 - WARNING :: Thread-2 : Failed to access uri endpoint /:/prefs. Is your server maybe accepting SSL connections only? HTTPConnectionPool(host='127.0.0.1', port=32400): Max retries exceeded with url: /:/prefs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f825390>: Failed to establish a new connection: [Errno 61] Connection refused',))
2018-06-11 03:10:21 - WARNING :: Thread-2 : Tautulli Pmsconnect :: Unable to parse XML for get_local_server_name: 'NoneType' object has no attribute 'getElementsByTagName'.
2018-06-11 03:10:21 - INFO    :: Thread-2 : Tautulli NotificationHandler :: Preparing notifications for notifier_id 1.
2018-06-11 03:10:34 - INFO    :: MainThread : Signal 15 caught, saving and exiting...
2018-06-11 03:10:35 - INFO    :: MainThread : Tautulli WebSocket :: Disconnecting websocket...
2018-06-11 03:10:35 - INFO    :: Thread-2 : Tautulli Notifiers :: Slack notification sent.
2018-06-11 03:10:36 - INFO    :: Thread-1 : Tautulli NotificationHandler :: Notification thread exiting...
2018-06-11 03:10:37 - INFO    :: MainThread : Tautulli Config :: Writing configuration to file

**Comment by JonnyWong16** [comment]
https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#general-q20
